export const createEmpresaFormConfig = {
  1: [
    { name: "nit", label: "Nit", type: "text", readOnly: false },
    { name: "nombre", label: "Nombre", type: "text", readOnly: false },
    { name: "email_contacto", label: "Correo Contacto", type: "email", readOnly: false },
    { name: "telefono", label: "Telefono", type: "number", readOnly: false },
    { name: "id_departamento", label: "Departamento", type: "select", readOnly: false },
    { name: "id_ciudad", label: "Ciudad", type: "select", readOnly: false },
    { name: "direccion", label: "Direccion", type: "text", readOnly: false },
    { name: "documento_representante", label: "Documento Representante", type: "number", readOnly: false },
    { name: "nombre_representante", label: "Nombre Representante", type: "text", readOnly: false },
    { name: "telefono_representante", label: "Telefono Representante", type: "text", readOnly: false },
    { name: "email_representante", label: "Correo Representante", type: "email", readOnly: false },

    { name: "admin_primer_nombre", label: "Primer Nombre Admin", type: "text", readOnly: false },
    { name: "admin_segundo_nombre", label: "Segundo Nombre Admin", type: "text", readOnly: false },
    { name: "admin_primer_apellido", label: "Primer Apellido Admin", type: "text", readOnly: false },
    { name: "admin_segundo_apellido", label: "Segundo Apellido Admin", type: "text", readOnly: false },
    { name: "admin_documento", label: "Documento Admin", type: "number", readOnly: false },
    { name: "admin_email", label: "Correo Admin", type: "email", readOnly: false },
    { name: "admin_telefono", label: "Telefono Admin", type: "number", readOnly: false },
    { name: "admin_direccion", label: "Direccion Admin", type: "text", readOnly: false },
    { name: "admin_password", label: "Contraseña Admin", type: "password", readOnly: false },
  ],
  2: [
    { name: "nit", label: "Nit", type: "text", readOnly: true },
    { name: "nombre", label: "Nombre", type: "text", readOnly: true },
    { name: "email_contacto", label: "Correo Contacto", type: "email", readOnly: false },
    { name: "telefono", label: "Telefono", type: "number", readOnly: false },
    { name: "direccion", label: "Direccion", type: "text", readOnly: false },
    { name: "documento_representante", label: "Documento Representante", type: "number", readOnly: true },
    { name: "nombre_representante", label: "Nombre Representante", type: "text", readOnly: false },
    { name: "telefono_representante", label: "Telefono Representante", type: "number", readOnly: false },
    { name: "email_representante", label: "Correo Representante", type: "email", readOnly: false },

    { name: "admin_primer_nombre", label: "Primer Nombre Admin", type: "text", readOnly: false },
    { name: "admin_segundo_nombre", label: "Segundo Nombre Admin", type: "text", readOnly: false },
    { name: "admin_primer_apellido", label: "Primer Apellido Admin", type: "text", readOnly: false },
    { name: "admin_segundo_apellido", label: "Segundo Apellido Admin", type: "text", readOnly: false },
    { name: "admin_documento", label: "Documento Admin", type: "number", readOnly: true },
    { name: "admin_email", label: "Correo Admin", type: "email", readOnly: false },
    { name: "admin_telefono", label: "Telefono Admin", type: "number", readOnly: false },
    { name: "admin_direccion", label: "Direccion Admin", type: "text", readOnly: false },
    { name: "admin_password", label: "Contraseña Admin", type: "password", readOnly: true },
  ],
};