export const createEmpresaFormConfig = {
  1: [
    { name: "nit", label: "Nit", type: "text", readOnly: false, icon: "badge", placeholder: "Ej: 900123456" },
    { name: "nombre", label: "Nombre", type: "text", readOnly: false, icon: "business", placeholder: "Ej: Mi Empresa S.A." },
    { name: "email_contacto", label: "Correo Contacto", type: "email", readOnly: false, icon: "mail", placeholder: "contacto@empresa.com" },
    { name: "telefono", label: "Telefono", type: "number", readOnly: false, icon: "phone", placeholder: "Ej: 3001234567" },
    { name: "id_departamento", label: "Departamento", type: "select", readOnly: false, icon: "map", placeholder: "Seleccione un departamento" },
    { name: "id_ciudad", label: "Ciudad", type: "select", readOnly: false, icon: "location_city", placeholder: "Seleccione una ciudad" },
    { name: "direccion", label: "Direccion", type: "text", readOnly: false, icon: "home_pin", placeholder: "Ej: Carrera 10 # 20-30" },
    { name: "documento_representante", label: "Documento Representante", type: "number", readOnly: false, icon: "badge", placeholder: "Ej: 10101010" },
    { name: "nombre_representante", label: "Nombre Representante", type: "text", readOnly: false, icon: "person", placeholder: "Ej: Juan Perez" },
    { name: "telefono_representante", label: "Telefono Representante", type: "text", readOnly: false, icon: "phone_iphone", placeholder: "Ej: 3101234567" },
    { name: "email_representante", label: "Correo Representante", type: "email", readOnly: false, icon: "contact_mail", placeholder: "juan.perez@empresa.com" },

    { name: "admin_primer_nombre", label: "Primer Nombre Admin", type: "text", readOnly: false, icon: "person", placeholder: "Ej: Miguel" },
    { name: "admin_segundo_nombre", label: "Segundo Nombre Admin (Opcional)", type: "text", readOnly: false, icon: "person", placeholder: "Ej: Andres" },
    { name: "admin_primer_apellido", label: "Primer Apellido Admin", type: "text", readOnly: false, icon: "person", placeholder: "Ej: Gomez" },
    { name: "admin_segundo_apellido", label: "Segundo Apellido Admin (Opcional)", type: "text", readOnly: false, icon: "person", placeholder: "Ej: Silva" },
    { name: "admin_documento", label: "Documento Admin", type: "number", readOnly: false, icon: "badge", placeholder: "Ej: 20202020" },
    { name: "admin_email", label: "Correo Admin", type: "email", readOnly: false, icon: "mail", placeholder: "admin@empresa.com" },
    { name: "admin_telefono", label: "Telefono Admin", type: "number", readOnly: false, icon: "phone", placeholder: "Ej: 3201234567" },
    { name: "admin_direccion", label: "Direccion Admin", type: "text", readOnly: false, icon: "home_pin", placeholder: "Ej: Calle 50 # 10-20" },
    { name: "admin_password", label: "Contraseña Admin", type: "password", readOnly: false, icon: "lock", placeholder: "Ingrese contraseña segura" },
  ],
  2: [
    { name: "nit", label: "Nit", type: "text", readOnly: true, icon: "badge", placeholder: "Ej: 900123456" },
    { name: "nombre", label: "Nombre", type: "text", readOnly: true, icon: "business", placeholder: "Ej: Mi Empresa S.A." },
    { name: "email_contacto", label: "Correo Contacto", type: "email", readOnly: false, icon: "mail", placeholder: "contacto@empresa.com" },
    { name: "telefono", label: "Telefono", type: "number", readOnly: false, icon: "phone", placeholder: "Ej: 3001234567" },
    { name: "direccion", label: "Direccion", type: "text", readOnly: false, icon: "home_pin", placeholder: "Ej: Carrera 10 # 20-30" },
    { name: "documento_representante", label: "Documento Representante", type: "number", readOnly: true, icon: "badge", placeholder: "Ej: 10101010" },
    { name: "nombre_representante", label: "Nombre Representante", type: "text", readOnly: false, icon: "person", placeholder: "Ej: Juan Perez" },
    { name: "telefono_representante", label: "Telefono Representante", type: "number", readOnly: false, icon: "phone_iphone", placeholder: "Ej: 3101234567" },
    { name: "email_representante", label: "Correo Representante", type: "email", readOnly: false, icon: "contact_mail", placeholder: "juan.perez@empresa.com" },

    { name: "admin_primer_nombre", label: "Primer Nombre Admin", type: "text", readOnly: false, icon: "person", placeholder: "Ej: Miguel" },
    { name: "admin_segundo_nombre", label: "Segundo Nombre Admin (Opcional)", type: "text", readOnly: false, icon: "person", placeholder: "Ej: Andres" },
    { name: "admin_primer_apellido", label: "Primer Apellido Admin", type: "text", readOnly: false, icon: "person", placeholder: "Ej: Gomez" },
    { name: "admin_segundo_apellido", label: "Segundo Apellido Admin (Opcional)", type: "text", readOnly: false, icon: "person", placeholder: "Ej: Silva" },
    { name: "admin_documento", label: "Documento Admin", type: "number", readOnly: true, icon: "badge", placeholder: "Ej: 20202020" },
    { name: "admin_email", label: "Correo Admin", type: "email", readOnly: false, icon: "mail", placeholder: "admin@empresa.com" },
    { name: "admin_telefono", label: "Telefono Admin", type: "number", readOnly: false, icon: "phone", placeholder: "Ej: 3201234567" },
    { name: "admin_direccion", label: "Direccion Admin", type: "text", readOnly: false, icon: "home_pin", placeholder: "Ej: Calle 50 # 10-20" },
    { name: "admin_password", label: "Contraseña Admin", type: "password", readOnly: true, icon: "lock", placeholder: "No se puede editar" },
  ],
};