<?php
require __DIR__.'/vendor/autoload.php';
$app = require_once __DIR__.'/bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

use Illuminate\Support\Facades\DB;

try {
    DB::statement('DROP FUNCTION IF EXISTS public.guardar_historial_admins() CASCADE;');
    DB::statement('DROP FUNCTION IF EXISTS public.guardar_historial_empresa() CASCADE;');
    
    $sql = "SELECT table_name, column_name FROM information_schema.columns WHERE identity_generation = 'ALWAYS' AND table_schema = 'public'";
    $results = DB::select($sql);
    foreach($results as $row) {
        $alterSql = "ALTER TABLE {$row->table_name} ALTER COLUMN {$row->column_name} SET GENERATED BY DEFAULT";
        DB::statement($alterSql);
        echo "Altered {$row->table_name}.{$row->column_name} to GENERATED BY DEFAULT\n";
    }
    echo "All identity columns converted successfully!\n";
} catch (\Exception $e) {
    echo "Error: " . $e->getMessage() . "\n";
}
